Repository iamAyushChamoli/hacktoberfest-24, pull requests merged in 2024-10, with the labels that each got.

#25 added link behaviour in learn more benefits section
  abt/Badge.md
  abt/Compete.md
  abt/Explore.md
  abt/GithHub_Git.md
  abt/Network.md
  abt/Portfolio.md
  package-lock.json
  src/components/Benefits.jsx
  src/constants/index.js
Labels: hacktoberfest-accepted

#28 issue-hayagreevanv-#28
  src/components/Benefits.jsx
Labels: hacktoberfest-accepted

#39 issue-hayagreevanv-#38
  src/participants/avatars/img/HayagreevanV.png
  src/participants/avatars/index.js
  src/participants/participants.js
Labels: participation-eligible, hacktoberfest-accepted

#37 FIX: Increased Footer Icons size -Umesh Kumar -#37
  src/components/Footer.jsx
Labels: hacktoberfest-accepted

#49 Added Name in Participation.js file
  src/participants/avatars/img/umesh.png
  src/participants/avatars/index.js
  src/participants/participants.js
Labels: participation-eligible, hacktoberfest-accepted

#61 Responsive Navbar
  package-lock.json
  package.json
  src/components/Header.jsx
  src/components/Heading.jsx
  src/components/Leaderboard.jsx
  src/constants/scroll.js
  src/index.css
Labels: hacktoberfest-accepted

#62 pr-add-mohitranag18-57
  src/participants/avatars/img/mohit.jpg
  src/participants/avatars/index.js
  src/participants/participants.js
Labels: participation-eligible, hacktoberfest-accepted

#64 pr-add-tanuj-64
  abt/Compete.md
Labels: hacktoberfest-accepted

#73 Added Contributor
  src/participants/avatars/img/pratikM.jpg
  src/participants/avatars/index.js
  src/participants/participants.js
Labels: participation-eligible, hacktoberfest-accepted

#87 pr-add-tanuj-87
  src/participants/avatars/img/tanuj.jpg
  src/participants/avatars/index.js
  src/participants/participants.js
Labels: participation-eligible, hacktoberfest-accepted

#89 Updated Badges.md
  abt/Badge.md
Labels: participation-eligible, hacktoberfest-accepted

#90 pr-update-Umesh Kumar
  src/participants/participants.js
Labels: active-eligible, hacktoberfest-accepted

#91 pr-add-RishaubKumar
  abt/Explore.md
Labels: hacktoberfest-accepted

#92 pr-add-ayushimaithani-40
  src/assets/svg/ClipPath.jsx
  src/components/Benefits.jsx
Labels: hacktoberfest-accepted

#94 pr-add-RishaubKumar
  package-lock.json
  src/participants/avatars/index.js
  src/participants/divyanshu.js
  src/participants/hayagreevanv.js
  src/participants/index.js
  src/participants/mohit.js
  src/participants/participants.js
  src/participants/pratikM.js
  src/participants/tanuj.js
  src/participants/uday.js
  src/participants/umesh.js
  src/participants/vineet.js
Labels: participation-eligible, hacktoberfest-accepted

#100 issue-kaushikikhabri-84
  src/components/Leaderboard.jsx
  src/index.css
Labels: participation-eligible, hacktoberfest-accepted

#99 issue-Lokeshsuwalka05
  src/components/Badges.jsx
Labels: participation-eligible, hacktoberfest-accepted

#105 UPDATE : Updated Umesh.js file
  src/participants/umesh.js
Labels: active-eligible, hacktoberfest-accepted

#110 reagarding issue #109
  README.md
Labels: participation-eligible, hacktoberfest-accepted

#113 Regarding issue #112
  CONTRIBUTING.md
Labels: participation-eligible, hacktoberfest-accepted

#120 pr-add-ashish5kmax-120
  src/participants/ashish_kumar_sahoo.js
  src/participants/avatars/img/ashish_kumar_sahoo.jpg
Labels: participation-eligible

#132 changes done in footer
  src/components/Footer.jsx
Labels: participation-eligible, hacktoberfest-accepted

#141 issue-AnasAli30-139
  README.md
  src/components/Header.jsx
  src/components/Hero.jsx
  src/participants/Anas.js
  src/participants/avatars/img/Anas.jpg
  src/participants/index.js
Labels: participation-eligible, hacktoberfest-accepted

#143 issue-AnasAli30-142
  README.md
  src/components/BadgeList.jsx
  src/participants/Anas.js
Labels: participation-eligible, hacktoberfest-accepted

#146 pr-add-mohitranag18-145
  src/participants/mohit.js
Labels: active-eligible, master-eligible
